-17.518072289156628
[6, 1, 4, 94442, 116, 3983765]
15.216666666666667
5
-9.11111111111111
[3, 26, 6525274, 2269538]
[3, 26, 6525274, 2269538]
[3, 26, 6525274, 2269538]
-8.428571428571429
-37
16
[8, 8, 4, 96, 3, 2747]
[8, 8, 4, 96, 3, 2747]
[8, 8, 4, 96, 3, 2747]
[8, 8, 4, 96, 3, 2747]
[8, 8, 4, 96, 3, 2747]
[8, 8, 4, 96, 3, 2747]
19
-6
19
19
19
19
40.857142857142854
Traceback (most recent call last):
  File [35m"/testcase.py"[0m, line [35m100[0m, in [35m<module>[0m
    for it0 in [31mrange[0m[1;31m(1,6)[0m:
               [31m~~~~~[0m[1;31m^^^^^[0m
[1;35mTypeError[0m: [35mrange expected at most 3 arguments, got 1343309766[0m
