9.633333333333333
[5, 7, 72, 26988, 6994357396]
9.633333333333333
[5, 7, 72, 26988, 6994357396]
[4, 5, 6494, 536, 183997]
[4, 5, 6494, 536, 183997]
-169.8
-169.8
-10.5
[5, 6, 5, 5, 497, 2275]
34
Error: RuntimeError: Out of bounds memory access (evaluating 'instance.exports._start()')
Stack: python.wasm.wasm-function[_Py_dict_lookup]@[wasm code]
python.wasm.wasm-function[insertdict]@[wasm code]
python.wasm.wasm-function[setitem_take2_lock_held]@[wasm code]
python.wasm.wasm-function[PyDict_SetItem]@[wasm code]
python.wasm.wasm-function[_PyModule_ClearDict]@[wasm code]
python.wasm.wasm-function[_PyModule_Clear]@[wasm code]
python.wasm.wasm-function[finalize_modules]@[wasm code]
python.wasm.wasm-function[_Py_Finalize]@[wasm code]
python.wasm.wasm-function[Py_FinalizeEx]@[wasm code]
python.wasm.wasm-function[Py_RunMain]@[wasm code]
python.wasm.wasm-function[pymain_main]@[wasm code]
python.wasm.wasm-function[Py_BytesMain]@[wasm code]
python.wasm.wasm-function[main]@[wasm code]
python.wasm.wasm-function[__main_void]@[wasm code]
python.wasm.wasm-function[_start]@[wasm code]
start@module-ready-wasi-py.js:498:32
@module-ready-wasi-py.js:5225:15
